In [1]:
import numpy as np
from scipy.sparse import spdiags
from scipy.linalg import toeplitz

Python version of KTBC.m

In [2]:
def KTBC(n):
    
    #E = np.diag(np.ones(n-1), 1)
    #K = 2 * np.eye(n) - E - E.T

    K = toeplitz([2, -1, *np.zeros(n-2)])
    T = K.copy()
    T[0][0] = 1
    B = T.copy()
    B[n-1][n-1] = 1
    C = K.copy()
    C[0][n-1] = -1
    C[n-1][0] = -1
    
    return K,T,B,C

Example: 

In [3]:
K,T,B,C = KTBC(4)
print(K)
print(T)
print(B)
print(C)

[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]
[[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]
[[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  1.]]
[[ 2. -1.  0. -1.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [-1.  0. -1.  2.]]


Python version of sparseKTBCcode.m

THIS IS THE CODE TO CREATE K,T,B,C AS SPARSE MATRICES

Then Matlab will not operate on all the zeros! 

In [4]:
def sparseKTBC(dtype = 'K', n = 10, sparse = False):
    """
    sparceKTBC Create finite difference model matrix.
    K=sparseKTBC(DTYPE,N,SPARSE) creates model matrix TYPE
    of size N-by-N. TYPE is one of the characters 'K', 'T'
    'B', or 'C'. The matrix is dense unless SPARSE is true.

    K=FDMODEL uses the defaults TYPE='K', N=10, and
    SPARSE=false.
    """
    e = np.ones(n)
    K = spdiags([[*-e], [*2*e], [*-e]], [-1,0,1], n, n, format='lil')
    if dtype == 'K':
        None
    elif dtype == 'T':
        K[0,0] = 1
    elif dtype == 'B':
        K[0,0] = 1
        K[n-1,n-1] = 1
    elif dtype == 'C':
        K[0,n-1] = -1
        K[n-1,0] = -1
    else:
        print('Unknown matrix type.')
            
    if sparse == False:
        return K.toarray()
    else:
        return K

Example:

In [5]:
K = sparseKTBC(dtype='K', n=4)
print('K4')
print(K)
T = sparseKTBC(dtype='T', n=4)
print('T4')
print(T)
B = sparseKTBC(dtype='B', n=4, sparse=True)
print('B4')
print(B)
C = sparseKTBC(dtype='C', n=4, sparse=True)
print('C4_sparse')
print(C)

K4
[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]
T4
[[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]
B4
  (0, 0)	1.0
  (0, 1)	-1.0
  (1, 0)	-1.0
  (1, 1)	2.0
  (1, 2)	-1.0
  (2, 1)	-1.0
  (2, 2)	2.0
  (2, 3)	-1.0
  (3, 2)	-1.0
  (3, 3)	1.0
C4_sparse
  (0, 0)	2.0
  (0, 1)	-1.0
  (0, 3)	-1.0
  (1, 0)	-1.0
  (1, 1)	2.0
  (1, 2)	-1.0
  (2, 1)	-1.0
  (2, 2)	2.0
  (2, 3)	-1.0
  (3, 0)	-1.0
  (3, 2)	-1.0
  (3, 3)	2.0
